### ISSUE TITLE
Coracle Nostur Nostrudel borked profile

### ISSUE THREAD

**Issue by alltheseas** [nostrability/nostrability#19] opened 2024-02-19 19:46 UTC
## client initiating action

unknown

## client receiving or observing action (or lack thereof)

Appears borked on Coracle, and Nostur. Not on Damus, and nostrudel.

## timestamp

https://njump.me/nevent1qqs89qsthp5epuy2g66t42jl4h40sujxmwm69j5v6txuw9ye9c245fgpr3mhxue69uhkummnw3ezucnfw33k76twv4ezuum0vd5kzmqpr3mhxue69uhkummnw3ezumt4w35ku7thv9kxcet59e3k7mgprpmhxue69uhhyetvv9ujuumwdae8gtnnda3kjctvqy2hwumn8ghj7etyv4hzumn0wd68ytnvv9hxgnw0pzw

## what happens 

> Coracle and Nostur both haved stopped working with my account.
When I use another account, everything works fine. So I make the assumption there is some related data to my account which is breaking things in those clients...it's not fun when you suddenly you can't use two of your favorite Nostr clients anymore. 😢 For now...

> I think I've broke Nostr in someway in my case: both Coracle (desktop) and Nostur (iOS) have stopped loading my feed. Damus (iOS) and noStrudel (desktop) seems to work fine.
On Coracle I'm getting a lot of errors which look related to reading out events from relays. When I use an other Nostr account, everything just works fine.

> and I already poked @staab  (npub1jlr…ynqn) about this 🤓

> Earlier this week I've used https://delete.nostr.com/ to delete some events with short text notes. Could there be a correlation between those actions and the issues I'm facing in Coracle and Nostur?

## suggestion

@mikedilger suggests 

> bug in a library [coracle & nostur] both use

Https://njump.me/nevent1qqsz72nw99lkzn686hsva23tajgk8xrgj34jt9l7aksthe9jxr69mxgpr4mhxue69uhkummnw3ez6ur4vgh8wetvd3hhyer9wghxuet5qyfhwumn8ghj7mmxve3ksctfdch8qatz9uq3wamnwvaz7tmjv4kxz7fwdehhxarj9e3xzmny9uq32amnwvaz7tmjv4kxz7fwv3sk6atn9e5k7tcdscak2

**Comment by alltheseas** [comment] 2024-02-19 19:49
@fabianfabian

**Comment by alltheseas** [comment] 2024-02-19 19:51
@sebastix

**Comment by Sebastix** [comment] 2024-02-19 20:00
@alltheseas It's fixed in Coracle by @staab 

Nostur is still broken for me and I've stopped using the app (which is a pity)

noStrudel is also having an issue here loading my following list:
https://nostrudel.ninja/#/u/npub1qe3e5wrvnsgpggtkytxteaqfprz0rgxr8c3l34kk3a9t7e2l3acslezefe/following

```
Something went wrong: Invalid byte sequence
```

@hzrd149

**Comment by staab** [comment] 2024-02-19 20:07
The root cause was an empty petname tag (`["p"]`) getting added to his follow list.

**Comment by alltheseas** [comment] 2024-02-19 20:23
> The root cause was an empty petname tag (`["p"]`) getting added to his follow list.

Was this caused by Coracle, or another app?

**Comment by staab** [comment] 2024-02-19 20:39
Pretty sure it wasn't Coracle, I couldn't say who though.

**Comment by fabianfabian** [comment] 2024-02-21 10:49
I'm still not sure what exactly cause is. @Sebastix do you still have the issue now with your current follow list? (id: f36c42a40edacc5606770e3b73be5dd70bf653852051414687726dda6e873db5)

> The root cause was an empty petname tag (["p"]) getting added to his follow list.

@staab do you mean the petname field was empty or the entire p tag was literally just ["p"] ?

**Comment by staab** [comment] 2024-02-21 12:20
The whole p-tag was empty, because my code failed when it expected to find a string, but found undefined as the tag value.

**Comment by Sebastix** [comment] 2024-02-21 12:28
@fabianfabian 
https://nostrudel.ninja/#/u/npub1qe3e5wrvnsgpggtkytxteaqfprz0rgxr8c3l34kk3a9t7e2l3acslezefe/following the issue has been resolved!

**Comment by alltheseas** [comment] 2024-02-21 12:48
@fabianfabian can you confirm the problem and solution, ser

**Comment by fabianfabian** [comment] 2024-02-21 13:24
I wish I could but I think the problem was something else and I don’t know what, at least on the Nostur side. I just tried publishing with an empty “p” and it seems to get rejected by relays ("invalid: unexpected size for fixed-size tag”), which is good. Forcing to handle an empty p on a local test relay just ignores the p and everything still works. Maybe there was something else in the tag that would also cause it to appear undefined on Coracle.

Best would be if we could find the kind 3 event that broke things but that may be difficult to find.

**Comment by Sebastix** [comment] 2024-02-21 13:30
@fabianfabian @alltheseas Sorry, I swapped noStrudel and Nostur here. My bad.

The issue is resolved on noStrudel /cc @hzrd149 

I reinstalled Nostur (iOS 17.3.1) from the App Store (1.12.0) and my feed is loading correctly now.

**Comment by Sebastix** [comment] 2024-02-22 08:57
@fabianfabian I still do have issues in Nostur. Afaik I only can see my own events in the feed, events I interacted with or events where I'm tagged at.

**Comment by fabianfabian** [comment] 2024-02-22 10:14
> @fabianfabian I still do have issues in Nostur. Afaik I only can see my own events in the feed, events I interacted with or events where I'm tagged at.

Does it still show you are following people in the sidebar or 0? 
![image](https://github.com/nostrability/nostrability/assets/343640/125940cf-5cc4-4cdf-85b6-60976c947dac)

**Comment by Sebastix** [comment] 2024-02-22 14:17
@fabianfabian I have a number of 451 following people there.

**Comment by alltheseas** [comment] 2024-02-23 21:18
@hzrd149 comment:

> I'm not sure exactly what the bug was, but I suspect it was similar to coracle in that the app was not expecting an empty "p" tag. its difficult to recreate though

**Comment by Sebastix** [comment] 2024-02-23 22:01
@fabianfabian I switched to Nostur on Testflight and I'm happy to say that version has working again as expected.

**Comment by alltheseas** [comment] 2024-02-26 16:51
@Sebastix are we good to close this issue now?

**Comment by Sebastix** [comment] 2024-02-26 18:50
@alltheseas Sure!

**Closed** 2024-02-26 20:06 UTC
Labels: coracle, nostur, nostrudel
