### ISSUE TITLE
Zapping a reply to your note from Primal triggers Zap push notification to OP in Damus

### ISSUE THREAD

**Issue by UTXOnly** [nostrability/nostrability#119] opened 2024-10-26 20:03 UTC
## client initiating action
Primal iOS version `1.9.9.1`

## client receiving or observing action (or lack thereof)
Damus iOS version `1.10.1 (1) f92509fd`

## timestamp
`1729969349`

## what happens 

When Zapping a reply to my note from Primal using Primal wallet in iOS app, I receive a zap push notification from Damus indicating that I have received a zap from myself.

### Example:

When I zapped this reply to my original post using Primal iOS + built-in Primal wallet:

```json
{
  "kind": 1,
  "id": "8d1102100a3725bcf8a639725b0faf8b3688529e8d30a4ef41c22a6bd3c6a0fe",
  "pubkey": "8a44facb32f4ecb62d88555b22ab5da6178df5dacd8257a8f9e1a21147103346",
  "created_at": 1729967966,
  "tags": [
    [
      "e",
      "5651f5748ba2bd55abc77157dd641b402e2c58504c817ee38895ea99e07235c1",
      "",
      "root"
    ],
    [
      "p",
      "4503baa127bdfd0b054384dc5ba82cb0e2a8367cbdb0629179f00db1a34caacc"
    ]
  ],
  "content": "You might be getting to the age you start liking coleslaw too. ",
  "sig": "665003e8abf8594977ab9fbf89f4e4a5ad3a2bd21ac25224dac24c3a6691e72c06ce2f08a860bb26fa1f46b3447ca6d0d3b3c0bc30b4c77394b6a8afe424791d"
}
```
The kind `9735` zap  receipt note below is generated:

```json
{
  "id": "75d7ac4a8f9750942c20ff2eff8a1f013a4175656bea887213666c82768130d1",
  "pubkey": "79f00d3f5a19ec806189fcab03c1be4ff81d18ee4f653c88fac41fe03570f432",
  "kind": 9735,
  "created_at": 1729969349,
  "tags": [
    [
      "p",
      "8a44facb32f4ecb62d88555b22ab5da6178df5dacd8257a8f9e1a21147103346"
    ],
    [
      "e",
      "8d1102100a3725bcf8a639725b0faf8b3688529e8d30a4ef41c22a6bd3c6a0fe"
    ],
    [
      "P",
      "4503baa127bdfd0b054384dc5ba82cb0e2a8367cbdb0629179f00db1a34caacc"
    ],
    [
      "bolt11",
      "lnbc210n1pn360xpdq87z06fgcnp4qg79j8kuzq74fu3sxmqn985l09jnwhvqh6wv8gvj0w2hudmcclfdqpp5mpl6re4ukk4nacgcchaw4m8g89vdhmr4yd6jc380euxwvc30jcuqsp5aurrt05sf4schu72zmxqautsvkfuamy28fy3efmccdelwap2hfcq9qyysgqcqpcxqyz5vqrzjqw9fu4j39mycmg440ztkraa03u5qhtuc5zfgydsv6ml38qd4azymlapyqqqqqqqra5qqqqlgqqqq86qqjqt6nks8yyfcf7965vchp77g7tuaant5dkcxrcdjkyactp7gukaayspufs2erunp29y03e3jlaw2p4jck8hfdjdfumk7nkr8c9fvrft2cqrqcn6d"
    ],
    [
      "preimage",
      "0d05102821737de0e01a05ece7890c08a19e55e7bdabff47f91b96795796e34d"
    ],
    [
      "description",
      "{\"id\":\"32c6e830d0f9fefd2e728fa04d57e138d2a90a6b9f2a2c05f15607a75caf1c8f\",\"pubkey\":\"4503baa127bdfd0b054384dc5ba82cb0e2a8367cbdb0629179f00db1a34caacc\",\"created_at\":1729969344,\"kind\":9734,\"tags\":[[\"p\",\"8a44facb32f4ecb62d88555b22ab5da6178df5dacd8257a8f9e1a21147103346\"],[\"e\",\"8d1102100a3725bcf8a639725b0faf8b3688529e8d30a4ef41c22a6bd3c6a0fe\"],[\"amount\",\"21000\"],[\"relays\",\"wss://offchain.pub\",\"wss://relay.damus.io\",\"wss://dev.nostpy.lol\",\"wss://nos.lol\",\"wss://relay.mutinywallet.com\",\"wss://nostr.bitcoiner.social\",\"wss://nostr-pub.wellorder.net\",\"wss://nostr.wine\",\"wss://relay.nostpy.lol\",\"wss://wheat.happytavern.co\",\"wss://nostr.fmt.wiz.biz\",\"wss://nostr.oxtr.dev\"]],\"content\":\"🤣\",\"sig\":\"ce821787cd2aad11dd0cc3d6cdefa1670f2ad6e6c12d2f21d34208c84432ba36cbc855897f811913b2a6ee631774a7c9468053cc754e3b114d0afebee227fbe0\"}"
    ]
  ],
  "content": "🤣",
  "sig": "0f873e0bd0641dd40136e4df6467c2c0a444fa8369a234b140e052ee03d17b5eff0794c17bc52abf796f01fdd401712874f66652a3264f784b0a6d711fed3913"
}
```

And I receive a push notification from Damus indicating I have received a Zap from my own pubkey

![image](https://github.com/user-attachments/assets/0fc05699-9651-436f-b6a3-58ccdefef981)

Worth noting that this behavior only exists as a push notification, this **DOES NOT** appear in `Notifications > Zaps` within the Damus app.

Seems related to https://github.com/nostrability/nostrability/issues/94 and https://github.com/damus-io/damus/issues/2462

**Comment by alltheseas** [comment] 2024-10-26 23:33
Thanks for the detailed report @UTXOnly and cross referencing the issue in damus repo 💪💪 

@jb55 is tackling in 1.11 🙏

**Comment by jb55** [comment] 2024-10-27 01:38
duplicate of #2462

**Closed by jb55** 2024-10-27 01:38 UTC
