### ISSUE TITLE
Zaps received to coinOS do not show in damus, primall

### ISSUE THREAD

**Issue by alltheseas** [nostrability/nostrability#58] opened 2024-08-20 13:21 UTC
## client initiating action

Placeholder

## client receiving or observing action (or lack thereof)
Damus: no zap seen
Primal: no zap seen

## timestamp

https://njump.me/nevent1qqswepmnz3rfkwf8xhdcee93h4jylqsa97y8ue38mk2jhkke6jseqdcprpmhxue69uhhyetvv9ujuumwdae8gtnnda3kjctvqyg8wumn8ghj7mn0wd68ytnhd9hx2qgdwaehxw309ahx7uewd3hkcqgkwaehxw309aex2mrp0yhxummnw3ezucnpdejq96cj7u

## suggestion

**Comment by alltheseas** [comment] 2024-08-20 13:23
CoinOs context https://github.com/coinos/coinos-server/issues/62

**Comment by SamSamskies** [comment] 2024-08-20 13:41
the issue is with coinos' lnurl server https://github.com/coinos/coinos-server/issues/63. i just made a PR to fix it https://github.com/coinos/coinos-server/pull/64.

**Comment by SamSamskies** [comment] 2024-08-20 18:36
@alltheseas you can close this. Zaps are finally working with coinos lightning addresses!

https://github.com/coinos/coinos-server/pull/64

**Closed** 2024-08-20 20:53 UTC
Labels: zaps  ⚡, coinOS

**Comment by alltheseas** [comment] 2024-08-20 20:55
@SamSamskies lmk if more attention needed

**Comment by alltheseas** [comment] 2024-08-20 20:56
Thank you @asoltys
