### ISSUE TITLE
Coracle and Snort break Damus kind 3 relay list

### ISSUE THREAD

**Issue by alltheseas** [nostrability/nostrability#10] opened 2024-01-29 17:47 UTC
## client initiating action

Coracle

## client receiving or observing action (or lack thereof)

Damus 

## timestamp

https://njump.me/note154jyjmjeknrq9fzw36deg46lrvpenqagq2vxlqtjvtznn06z8pgq80lul5

## what happens 

> Heads up that if you use Coracle and also Damus, Damus will become unusable if you follow or unfollow anyone using Coracle. This is because Coracle will rug your non-standard kind 3 relay list. You’ll need to re-add your relays using Damus in order for Damus to start working again.

**Comment by alltheseas** [comment] 2024-01-29 17:49
@staab is there a way to fix, ser

cc @jb55

**Comment by SamSamskies** [comment] 2024-01-29 17:53
Fix is Damus starts using kind 10002 to obtain a user's relay list or Coracle stops nuking kind 3 relay list when following or unfollowing someone.

**Comment by staab** [comment] 2024-01-29 17:56
This is a feature not a bug. At least... I think so.

Ironically, this has been true for 9 months, during which time Damus hasn't upgraded to NIP 65, and kind 3 relays hasn't been added to the spec. Priorities, I know, not faulting anyone but it's a great case study in feature deprecation on nostr. I'm beginning to wonder if ETA for deprecations is actually going to be "never". I'm quickly losing hope for nip44 adoption.

**Comment by fiatjaf** [comment] 2024-01-29 19:00
Wasn't Damus storing caching things locally already in order to recover from these incidents?

**Comment by jb55** [comment] 2024-01-29 19:01
On Mon, Jan 29, 2024 at 11:00:26AM -0800, fiatjaf_ wrote:
>Wasn't Damus storing things locally already in order to recover from these incidents?

they are stored locally but I don't have the recovery bits yet.

**Comment by jb55** [comment] 2024-01-29 21:43
> Fix is Damus starts using kind 10002 to obtain a user's relay list or Coracle stops nuking kind 3 relay list when following or unfollowing someone.

many clients still use kind 3, so now we have to handle two things at once? which one should have the authority? what if one client publishes a 10002 list and another client has a different list in kind3? btw we publish 10002 when setting contact lists now, so we at least try to be maximally compatible with other clients.

**Comment by staab** [comment] 2024-01-29 22:24
> from the defacto-standard which was kind-3 relay lists for years

Is this true? I seem to remember Snort inventing kind 3 relays early last year, shortly before Mike proposed NIP 65.

Others may have different ideas on this, but in my mind the semantics of 3 and 10002 are the same. So you could update Damus to privilege over 10002 without fully implementing outbox (you'd basically just end up with a poor outbox implementation, which is fine).

Whether my assumption is true or not, the line from the NIP 65 spec doesn't really make sense because "client's usage of relays" is basically not defined. I could see lots of different ways that would work (always pull from these relays, pull from these by default, bootstrap using these). Coracle hardcodes defaults and pulls bootstrap relays from nostr.watch, so I have no use for kind 3 as distinct from 10002. It seems you agree @jb55 because you're publishing the same relay list to kind 3 and 10002.

**Comment by jb55** [comment] 2024-01-29 23:21
On Mon, Jan 29, 2024 at 02:25:06PM -0800, hodlbod wrote:
>> from the defacto-standard which was kind-3 relay lists for years
>
>Is this true? I seem to remember Snort inventing kind 3 relays early
>last year, shortly before Mike proposed NIP 65.

It was first used in branle, as well as many different clients

- astral.ninja
- a terminal one whos name I'm blanking on
- a few other web ones
- damus web

Then I adopted it in Damus, then other clients like Amethyst and snort
adopted it as well. It was not invented by Snort.

You can ignore and break all those all clients, but just because it
wasn't written up doesn't mean it wasn't a viable thing to use, because
it was the only thing to use at the time. It became a "de-facto"
standard.

This idea that I have to change something that was working fine for
years and add even more complexity to relay handling just because one
client wants to do something a new way is something I greatly detest.
This effectively means if I don't develop on the dev schedule of whoever
creates new NIPs at any given time, damus will effectively break
sometime in the future.

It honestly feels a bit like bitcoin-cash at this point, and it is
really putting me off from working on this protocol. I wish people
actually cared about upgrade paths instead of just breaking stuff to try
and force other clients to upgrade. This is such a terrible way to do
protocol development.

I'm at the point where I now have to treat other clients adversarially,
which was probably inevitable. I am working on protections in nostrdb
that will revert these kind of damages.

We will eventually switch to the new list when we have have a great need
for it and have an outbox-model-mode, but for now it's just busywork for
us when kind3 works fine for fixed relay lists and is widely deployed.
When damus makes large changes like this it can break a lot of existing
tooling, as clients tend to copy what damus does, so I have to do this
in a methodical and non-rushed way.

	Will

**Comment by staab** [comment] 2024-01-30 17:39
It's strange to me that we're having this conversation nearly a year after NIP 65 was introduced. Why didn't you participate in the conversation on https://github.com/nostr-protocol/nips/pull/218? Not to say you were obligated to, since you're right — new protocol features shouldn't break existing clients, and client devs shouldn't have to politic all the time to protect their stuff. But the issue of client compatibility wasn't brought up at all, and probably wasn't even on anyone's radar.

I think what I'm learning here is that not only do new protocol features need to backwards-compatible, implementations need to as well. The reason is that "upgrades" are not transitory as in traditional software development, they are perpetual. In other words, it seems like there is no such thing in nostr as a deprecation. If there is a way to do something, it is permanent. Deprecations rely on cathedral development, and we have a bazaar.

I'm willing to add better compatibility to Coracle if we can't work out a way to safely deprecate protocol features. But it's just a terrible state of affairs, because now everyone has to publish redundant relay selections, and there's no way to fix many things about nostr that cause broken user experiences.

**Comment by alltheseas** [comment] 2024-01-30 19:30
Also snort wipes kind3 @v0l 

Https://njump.me/note1y4whukp075t9r985hnd6ssu64x7w8kf7x0ga5f5uuwwtj6p9dq5sms6daz

**Comment by staab** [comment] 2024-01-30 22:30
Gossip doesn't wipe kind 3 content, but it doesn't keep it in sync with 10002 either.

**Comment by v0l** [comment] 2024-01-30 22:41
For the sake of @jb55's mental health i have added the relays back into kind3 https://github.com/v0l/snort/commit/07510d92cadd95dc961f695dde809333188e4366

**Comment by pablof7z** [comment] 2024-01-30 22:46
> Gossip doesn't wipe kind 3 content, but it doesn't keep it in sync with 10002 either.

I think this is the right balance:

if you simply don't remove data you don't understand you are backwards AND future-compatible.

**Comment by staab** [comment] 2024-01-31 14:03
> Gossip doesn't wipe kind 3 content, but it doesn't keep it in sync with 10002 either.

I agree that this is the correct balance. Deprecate, without damaging. I've added support for this approach in the next release of Coracle. Unfortunately it'll take a lot more refactoring to apply this technique more broadly, but at least this particular issue is fixed.

**Comment by pablof7z** [comment] 2024-01-31 14:39
It might make sense for us to write this somewhere in the protocol 🤔

**Comment by alltheseas** [comment] 2024-01-31 14:56
Is this a NIP upgrade, a new NIP, or a implementation best practice (excuse corporate speak)

**Comment by pablof7z** [comment] 2024-01-31 15:18
I'd say it's a soft suggestion; certainly not a NIP, maybe a best practice but who knows? Best practice sounds too strong. I'd phrase it as a "if you haven't thought about it maybe consider handling this issue this way"

**Comment by staab** [comment] 2024-01-31 15:32
Best practice is probably ok

**Comment by alltheseas** [comment] 2024-01-31 16:07
So where does this go? 

Should there be a "best practice", "fall back", "implied implementation (unless you have thought more about it" category in the nostr-protocol repo?

**Comment by staab** [comment] 2024-01-31 16:20
We could add a best practices document to the NIPs repo, but that would add contention to an already contentious document. Maybe it should live elsewhere, at nostrdesign.org or nostr.com or something.

**Comment by alltheseas** [comment] 2024-01-31 17:15
If yall want we can use nostrability.com

**Comment by staab** [comment] 2024-01-31 17:26
Just released the Coracle update, so we can close this I think.

**Closed** 2024-01-31 17:32 UTC
Labels: damus, coracle, snort, relay
