### ISSUE TITLE
Dilger relay - 3 nostr client AUTH misinteraction

### ISSUE THREAD

**Issue by alltheseas** [nostrability/nostrability#29] opened 2024-04-09 20:46 UTC
## client initiating action
Unknown - at least three clients

## client receiving or observing action (or lack thereof)
wss://chorus.mikedilger.com:444/
https://github.com/mikedilger/chorus/

## timestamp
http://njump.me/note1z7nzsf0nm7m2mgr6qytq4g6qa9slshxzmn9dwmkxhy7zyasztz0qq0uhy0

## what happens 
> To whom it may concern,

> Quite a few nostr clients connect to my relay and then don't submit a subscription request.  After 6 seconds I time them out.  I think they may be getting confused by the fact that I send them an AUTH right off the bat.  Clients should be able to tolerate AUTH messages, and ignore them if they don't care to authenticate.

> This happens with at least 3 clients because I've seen 3 different user-agent strings exhibit this behavior:
  Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Safari/537.36
  Go-http-client/1.1
  and clients that do not submit a user-agent

@mikedilger 

## suggestion

**Comment by alltheseas** [comment] 2024-04-09 20:48
Semisol:

> Agreed. Clients should just ignore AUTH until it’s necessary (they ask for DMs), or it’s a user added relay (say inbox relays). Snort is one client you can blame

@v0l

**Comment by mikedilger** [comment] 2024-04-09 21:03
https://snort.social is NOT doing this.
https://iris.to IS doing this.
https://next.nostrudel.ninja IS doing this.

Strictly speaking, they might have fired off a subscription and it was closed, but then they "hung around" without any open subscriptions until I timed them out.

This isn't necessarily broken behavior, but it is a clue that there might be broken behavior, and they could behave better IMHO.

**Comment by alltheseas** [comment] 2024-04-09 21:04
Are snort and iris not the same?

**Comment by mikedilger** [comment] 2024-04-09 21:21
Also https://primal.net

**Comment by alltheseas** [comment] 2024-04-09 21:52
@hzrd149 @mbrat1 @moyaa

**Comment by alltheseas** [comment] 2024-04-09 21:53
@mmalmi

**Comment by v0l** [comment] 2024-04-10 11:07
In snort `AUTH` will be ignored unless we requested DMS/GiftWraps from that relay.

Normally we do keep connections open for 30s unless they are being used for something, so if we fired off a request and it was closed then it will stay open for 30s more.

What you're seeing is probably a difference in somebody who uses this relay as their inbox vs somebody who is using this relay as an outbox, when this relay is used as an inbox from DMS then we will respond to `AUTH` after we expect it by issuing a query including kind 4/1059, otherwise `AUTH` is ignored

**Comment by v0l** [comment] 2024-04-10 11:09
> Semisol:
> 
> > Agreed. Clients should just ignore AUTH until it’s necessary (they ask for DMs), or it’s a user added relay (say inbox relays). Snort is one client you can blame
> 
> @v0l

semi didnt like that i added this `AUTH` logic because he wanted to `AUTH` all users regardless. Maybe we should allow automatic `AUTH` for a users own listed read/write relays idk.

**Comment by hzrd149** [comment] 2024-04-13 18:32
noStrudel currently ignores AUTH messages. I'm in the process of rebuilding the relay client code in the next.nostrudel.ninja version so it can start handling AUTH messages but it still doesn't do anything with them.

I did a quick test and added `wss://chorus.mikedilger.com:444/` to my list of relays in the app and I couldn't reproduce the issue where it would open a connection and not send any REQs. but I'm also in the middle of making some changes to how it loads timelines, so its possible that there was a bug in the next version when you tested it

**Comment by mikedilger** [comment] 2024-04-16 19:38
This report was just an observation that hinted at possible poor behavior, and often doesn't represent any bug or incompatibility.

I think we should open separate ones for each client only if we determine an incompatibility or bug.  So I'm going to close this, but reopen if you disagree.

**Closed by mikedilger** 2024-04-16 19:38 UTC
Labels: primal, relay, nostrudel, iris

**Comment by alltheseas** [comment] 2024-04-16 20:11
Thanks and agree Mike. I'm not aware of a better repo than this github today, and I am happy that the general observation can reside here for future dev reference.
