### ISSUE TITLE
zap stream wipes Mute list

### ISSUE THREAD

**Issue by alltheseas** [nostrability/nostrability#47] opened 2024-06-05 18:28 UTC
## client initiating action

Unclear

## timestamp

https://njump.me/nevent1qqstyv26dy7r40302rp4d70wxkxdexpavrazcmrw6w0alzuu0wgg9hguey202

## what happens 

> My mute list has been rugged twice in the past week. I suspect Damus as the culprit, but not sure.

> main suspects are Damus, Coracle, and Primal. Seems to always happen after using Damus, but not sure cause it takes a little while for me to realize my mute list was rugged.

> I have the same relay setup on my kind 3 and kind 10002

## suggestion

**Comment by alltheseas** [comment] 2024-06-10 18:19
https://njump.me/nevent1qqsps72lrznycvmkg3xruqxc6wmvpc0e6a0qn22zzgyjwpjxs27ww8cpr3mhxue69uhkummnw3ezumt4w35ku7thv9kxcet59e3k7mgpp4mhxue69uhkummn9ekx7mqpzemhxue69uhhyetvv9ujumn0wd68ytnzv9hxgqg5waehxw309aex2mrp0yhxgctdw4eju6t0nt4xcf

> I’m going to try an experiment and not use Damus for a few days and see if it happens again

**Comment by SamSamskies** [comment] 2024-06-12 21:36
I haven't figure out to recreate this yet, but I noticed that if I have any words that I've muted with Damus and then mute or unmute anyone using Primal, it removes the muted words from my mute list. 

Also, Listr thinks words are unsupported in a mute list. I'm guessing nip-51 was updated to include support for muting words and some clients have not updated their code to support this.

![Screenshot 2024-06-12 at 4 21 28 PM](https://github.com/nostrability/nostrability/assets/3655410/5c47ed8c-f444-445c-8f3d-939cb46236ba)

**Comment by SamSamskies** [comment] 2024-06-12 21:44
Primal also removes any muted threads from the mute list when muting or unmuting any user.

**Comment by SamSamskies** [comment] 2024-06-13 15:35
Just opened Damus and my muted list was rugged again.

**Comment by alltheseas** [comment] 2024-06-13 17:04
@SamSamskies how would you recommend steps to recreate to minimize complexity?

Sounds like I should use primal desktop with damus first, and check mute list outcome. If that doesnt do anything, I'll throw in coracle to the mix. 

I dont mind sacrificing my mute list for the cause.

**Comment by SamSamskies** [comment] 2024-06-13 19:00
I talked to someone else that tried an experiment yesterday and they only used Damus and their mute list was rugged this morning. 

This only seemed to have started happening when the ability to mute words started so make sure you have both muted words and users on your mute list. You could also try using the same relay set as me. My mute list was rugged again 40 min ago. Damus relay has an empty mute list again. wss://relay.primal.net still has my mute list that I restarted earlier this morning.

**Comment by SamSamskies** [comment] 2024-06-13 19:10
I'd also recommend making sure that Damus does not query wss://purplepag.es for mute lists, because it doesn't support mute lists and will always return nothing.

**Comment by alltheseas** [comment] 2024-06-24 04:20
@danieldaquino your assistance is requested in investigating damus being the culprit of wiping  cross app mute lists ser :pray:

**Comment by karnagebitcoin** [comment] 2024-06-25 01:27
Hey guys, chiming in. I tested this using Damus only for a day and my list was also rugged. Since then, it was rugged many more times but I am uncertain if I used anything else. I know one thing for sure is that it's not Snort or Iris because I have not used those for a while.

**Comment by jb55** [comment] 2024-06-25 16:56
On Mon, Jun 24, 2024 at 06:27:22PM GMT, Karnage wrote:
>Hey guys, chiming in. I tested this using Damus only for a day and my
>list was also rugged. Since then, it was rugged many more times but I
>am uncertain if I used anything else. I know one thing for sure is that
>it's not Snort or Iris because I have not used those for a while.

I've been muting and unmuting a lot today and haven't run into this
yet... hmm

it's likely the same issue with the contact list overwriting. we should
be able to fix that like we did with contact lists by retrieving the
list locally first.

**Comment by SamSamskies** [comment] 2024-06-25 17:10
> I've been muting and unmuting a lot today and haven't run into this yet... hmm

the weird thing is muting or unmuting doesn't seem to be the trigger to rug the mute list. the mute list just seems to reset to nothing every day.

**Comment by staab** [comment] 2024-06-25 17:39
I've also experienced this in Coracle. I've been keeping a close eye on it but am unable to find when the mute list gets cleared. I did change how mutes work recently, but it's still strange that the same issue would crop up in multiple places at the same time. Maybe relays are dropping mute lists?

**Comment by alltheseas** [comment] 2024-06-25 18:38
@staab are you using multiple apps as well? 

Damus had a contact list issue where relays have trouble with too many follows. This is a potential lead @danieldaquino is investigating

**Comment by staab** [comment] 2024-06-25 18:43
On occasion, but pretty lightly. I think I'm experiencing this only using Coracle.

**Comment by SamSamskies** [comment] 2024-06-25 19:25
It would be awesome if clients prompted a user for confirmation before publishing an empty mute list. Putting that in place might also help figure out what is causing the mute list to get rugged.

**Comment by karnagebitcoin** [comment] 2024-06-26 00:34
> > I've been muting and unmuting a lot today and haven't run into this yet... hmm
> 
> the weird thing is muting or unmuting doesn't seem to be the trigger to rug the mute list. the mute list just seems to reset to nothing every day.

This seems to be true. This morning I woke up, haven't done anything other than scroll the feed and reply a few times and noticed my mutes are totally cleared again.

**Comment by karnagebitcoin** [comment] 2024-06-26 00:35
> > > I've been muting and unmuting a lot today and haven't run into this yet... hmm
> > 
> > 
> > the weird thing is muting or unmuting doesn't seem to be the trigger to rug the mute list. the mute list just seems to reset to nothing every day.
> 
> This seems to be true. This morning I woke up, haven't done anything other than scroll the feed and reply a few times and noticed my mutes are totally cleared again.

on second thought, I did mute 1 person on zap.stream yesterday, and did not check my mute list since then. That could have been the trigger...

**Comment by alltheseas** [comment] 2024-06-26 08:28
> I did mute 1 person on zap.stream yesterday, and did not check my mute list since then. That could have been the trigger...

there is a known zap stream contact list wipe issue https://github.com/nostrability/nostrability/issues/26

**Comment by staab** [comment] 2024-06-26 18:01
Just went to zap.stream, and my mute list got wiped again. I think that's the source of the issue I'm experiencing.

**Comment by alltheseas** [comment] 2024-06-26 18:42
@v0l ser

**Comment by karnagebitcoin** [comment] 2024-06-26 22:15
> Just went to zap.stream, and my mute list got wiped again. I think that's the source of the issue I'm experiencing.

yeeeeep. same

**Comment by karnagebitcoin** [comment] 2024-06-26 22:17
I think Snort also wipes.

**Comment by v0l** [comment] 2024-06-27 12:10
private mute list or bust!

I thought i rolled it back already... maybe not for zap.stream

**Comment by karnagebitcoin** [comment] 2024-06-27 14:41
Maybe mute lists should all be local per client? Seems crazy that one opinionated implementation can break the experience across clients. 

Not as convenient locally, but at least doesn't break? 🤷‍♂️

**Comment by SamSamskies** [comment] 2024-06-27 15:18
i just went to zap.stream to confirm and it wipes your mute page as soon as the page loads. it's possible that's been the root cause for me this whole time.

**Comment by jb55** [comment] 2024-06-27 18:15
hmm even with encrypted mutes it shouldn't wipe the public mutes? unless you discard the public ones @v0l ?

**Comment by karnagebitcoin** [comment] 2024-06-27 23:31
> > Maybe mute lists should all be local per client? Seems crazy that one opinionated implementation can break the experience across clients.
> > Not as convenient locally, but at least doesn't break? 🤷‍♂️
> 
> Nein! This is the whole point of nostr and nostrability. We will fix it

The whole point of nostr is unified mute lists? lol.

It'll be great if it works, but then you're just one implementation away from breaking it all again?

**Comment by alltheseas** [comment] 2024-06-28 06:02
Yes - the whole point of nostr, and a thing no corpo gulag h can have is interoperability. 

We are not there yet. We'll see apps add more safety features. 

Ideally github.com/nostrCI runs interop tests automatically, so that we can catch issues before they affect users. 

I am still looking for a nostrCI dev.

**Comment by v0l** [comment] 2024-07-01 13:33
Pushed fix

**Comment by alltheseas** [comment] 2024-07-01 13:35
@karnagebitcoin can you test

cc @SamSamskies

**Comment by karnagebitcoin** [comment] 2024-07-01 13:47
> @karnagebitcoin can you test
> 
> cc @SamSamskies

works. Had to clear cache

**Comment by karnagebitcoin** [comment] 2024-07-01 13:50
Snort is still clearing the mutes

**Comment by v0l** [comment] 2024-07-01 13:52
@karnagebitcoin give it a few more mins, not released to snort yet

**Closed** 2024-07-01 13:53 UTC
Labels: damus, coracle, primal, zapstream, mute
